-- handoff:excluded targets the canonical/pipeline DB provisioned by scripts/setup.sql; depends on memory_entry_chunks which no per-project schema defines
-- Phase 3b: per-chunk contextual blurb storage.
-- Blurb is a ≤200-token description of the chunk's topic, generated by
-- qwen2.5:14b via Ollama. Prepended to chunk text at embed time to give
-- the embedder topic-anchored context. NULL = blurb not yet generated.
-- The blurb is NOT the chunk's content — memory_entry_chunks.content
-- remains the canonical source text.

ALTER TABLE memory_entry_chunks
  ADD COLUMN IF NOT EXISTS blurb TEXT;

COMMENT ON COLUMN memory_entry_chunks.blurb IS
  'Phase 3b: qwen2.5:14b-generated topic blurb prepended at embed time. NULL = not yet generated. Regenerate by NULLing then running pipeline-embed.js blurbs.';
